### ISSUE TITLE
Keep getting "Cannot resolve all parameters for..." error

### ISSUE THREAD

**Issue by galtalmor** [mgechev/injection-js#16]
I'm trying to use this in a node project written in TypeScript (tried running it with ts-node and with the code compiled to JS).
I've got to the point where I just copied the very basic example from the readme, and still get the same result.
I made sure 'reflect-metadata' and 'injection-js' both installed and on latest version.
What am I missing?

This is the code:
```
import 'reflect-metadata';
import { ReflectiveInjector, Injectable, Injector } from 'injection-js';

class Http {}

@Injectable()
class Service {
    constructor(private http: Http) {}
}

const injector = ReflectiveInjector.resolveAndCreate([
    Service,
    Http
]);

console.log(injector.get(Service) instanceof Service);
```

And this is the exception:
```
D:\proj>ts-node "./src/index.ts"

D:\proj\node_modules\injection-js\injection.bundle.js:684
    return Error('Cannot resolve all parameters for \'' + stringify(typeOrFunc) + '\'(' +
           ^
Error: Cannot resolve all parameters for 'Service'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Service' is decorated with Injectable.
    at noAnnotationError (D:\proj\node_modules\injection-js\injection.bundle.js:684:12)
    at _dependenciesFor (D:\proj\node_modules\injection-js\injection.bundle.js:1377:15)
    at resolveReflectiveFactory (D:\proj\node_modules\injection-js\injection.bundle.js:1277:24)
    at resolveReflectiveProvider (D:\proj\node_modules\injection-js\injection.bundle.js:1300:82)
    at Array.map (native)
    at resolveReflectiveProviders (D:\proj\node_modules\injection-js\injection.bundle.js:1307:31)
    at Function.ReflectiveInjector.resolve (D:\proj\node_modules\injection-js\injection.bundle.js:1504:16)
    at Function.ReflectiveInjector.resolveAndCreate (D:\proj\node_modules\injection-js\injection.bundle.js:1533:62)
    at Object.<anonymous> (D:\proj\src\index.ts:11:37)
    at Module._compile (module.js:571:32)
```

**Comment by mgechev** [comment]
You need the flag `emitDecoratorMetadata`.

**Comment by galtalmor** [comment]
Yep, now it works.
I think it's worth mentioning in the readme.
It would have saved me quite some time.
Thanks!

**Comment by mgechev** [comment]
@galtalmor would you open a PR?

**Comment by galtalmor** [comment]
Sure. Will do.

**Comment by kuriel-dev** [comment]
Facing same problem with this tsconfig.json:

```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  },
  "types": [
    "react",
    "react-native",
    "react-navigation",
    "jest"
  ]
}

```


Im ussing resolveAndCreate:

`       const injector = ReflectiveInjector.resolveAndCreate(lstServices);`


HttpService:

```
@Injectable()
export class HttpService {

    constructor(private storageService: StorageService) {
    }
```

StorageService:

```

@Injectable()
export class StorageService {
```

**Error:  Cannot resolve all parameters for 'HttpService'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'HttpService' is decorated with Injectable.**

**Comment by kuriel-dev** [comment]
Sorry, related to: https://github.com/mgechev/injection-js/issues/36

babel config.
